# do not use make as the current program works with OS interraption singal and signals do not work witn make correctly
# cpu: clean build
# 		./server -cpuprofile cpu.prof

# mem: clean build
# 		./server -memprofile mem.prof

# clean:
# 		rm -rf cpu.prof mem.prof

# cln: clean

# build:
# 	go1.15.5 build -o server .

# .PHONY: clean cln cpu mem build